version = "3.8.1"
runner.dialect = scala3
align.preset = most
align.tokens."+" = [
  { code = "=", owner = "Defn.(Val|Var|Def|Type)" },
  { code = "//", owner = ".*" }
]
maxColumn = 120
indent.defnSite = 2
indent.callSite = 2
docstrings.style = Asterisk
newlines.source = keep
rewrite.rules = [RedundantParens, SortImports]
spaces.inImportCurlyBraces = true
trailingCommas = always
